apiVersion: v1alpha
name: config
kind: Project
metadata:
  name: ${REPO_NAME}
spec:
  repository:
    url: ${REPO_URL}
    run: true
  schedulers:
    - name: build
      branch: master
      at: "0 */3 * * *"
      pipeline_file: ".semaphore/job.yml"
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
